/**
 * Exception Handling
 * 
 */

// ReferenceError: b is not defined
try {  
  let a = 1;  
  let c = a + b;  
} catch (e) {  
  console.log(e);  
} 

